[project]
name = "llvm-project"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
cmake = "*"
python = "3.12.*"
ninja = "*"
c-compiler = "*"
cxx-compiler = "*"
zlib = "*"
zstd = "*"
vswhere = "*"
libxml2 = "*"
vs_win-64 = "*"

[tasks]
flang = { cmd = ["conda/build_flang.bat"], description = "Build the project" }